import { StyleSheet } from 'react-native';

export const createLoginStyles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.BACKGROUND_COLOR,
      justifyContent: 'center',
      padding: 20,
      position: 'relative',
      overflow: 'hidden',
    },
    backgroundAnimation: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      top: 0,
      left: 0,
      zIndex: 0,
    },
    contentWrapper: {
      zIndex: 1,
      flex: 1,
      justifyContent: 'center',
    },
    header: {
      alignItems: 'center',
      marginBottom: 50,
    },
    themeToggle: {
      position: 'absolute',
      top: 20,
      right: 20,
      zIndex: 2,
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: theme.ACCENT_COLOR,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    themeToggleText: {
      fontSize: 24,
    },
    logo: {
      width: 120,
      height: 120,
      resizeMode: 'contain',
      marginBottom: 15,
    },
    titulo: {
      fontSize: 32,
      fontWeight: '700',
      color: theme.TEXT_COLOR,
      letterSpacing: 2,
    },
    subtitle: {
      fontSize: 13,
      color: theme.TEXT_COLOR,
      opacity: 0.7,
      marginTop: 8,
      fontStyle: 'italic',
    },
    card: {
      backgroundColor: theme.BACKGROUND_COLOR,
      borderRadius: 20,
      padding: 25,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
      borderWidth: 1,
      borderColor: theme.ACCENT_COLOR + '15',
    },
    label: {
      color: theme.TEXT_COLOR,
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 8,
      marginTop: 16,
      letterSpacing: 0.5,
    },
    input: {
      backgroundColor: theme.BACKGROUND_COLOR === '#F8F9FA' ? '#FFFFFF' : '#1A1F26',
      padding: 14,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.ACCENT_COLOR + '30',
      color: theme.TEXT_COLOR,
      fontSize: 14,
      fontWeight: '500',
      marginBottom: 4,
    },
    inputFocused: {
      borderColor: theme.ACCENT_COLOR,
      borderWidth: 2,
    },
    boton: {
      backgroundColor: theme.ACCENT_COLOR,
      padding: 16,
      borderRadius: 12,
      alignItems: 'center',
      marginTop: 35,
      shadowColor: theme.ACCENT_COLOR,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    botonPressed: {
      opacity: 0.85,
      transform: [{ scale: 0.98 }],
    },
    textoBoton: {
      color: '#FFFFFF',
      fontWeight: '700',
      fontSize: 15,
      letterSpacing: 1,
    },
    linkContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginTop: 20,
      gap: 5,
    },
    linkText: {
      color: theme.TEXT_COLOR,
      opacity: 0.7,
      fontSize: 12,
    },
    linkButton: {
      color: theme.ACCENT_COLOR,
      fontWeight: '600',
      fontSize: 12,
    },
  });
