export const THEME_LIGHT = {
    BACKGROUND_COLOR: '#F8F9FA',
    TEXT_COLOR: '#212529',
    ACCENT_COLOR: '#6B8AE3',
    SECONDARY_COLOR: '#E0E7FF',
    BORDER_COLOR: '#E9ECEF',
};


export const THEME_DARK = {
    BACKGROUND_COLOR: '#1A1F26',
    TEXT_COLOR: '#F8F9FA',
    ACCENT_COLOR: '#7C9EFF',
    SECONDARY_COLOR: '#2D3748',
    BORDER_COLOR: '#3A4556',
};